import Foundation

enum TripSeed {
    static let places: [Place] = [
        Place(id: "zurich", name: "Zurich", kind: "City / rail base", region: "Start / finish", latitude: 47.3769, longitude: 8.5417, role: "Arrival, work day, final base", note: "Workday start and evening departure point for Lucerne.", bestFor: "A low-stress arrival and logistics base.", allow: "2-4 evening hours if time allows.", dontMiss: ["Limmat river", "Lake Zurich", "Zurich HB"], practical: "Finish near Zurich HB if possible for a simple Lucerne train.", extraDetails: ["Use Zurich for arrival logistics, snacks, and rail setup.", "The route now avoids sleeping in Zurich at the start."]),
        Place(id: "lucerne", name: "Lucerne", kind: "Lake city / rail base", region: "Central Switzerland", latitude: 47.0502, longitude: 8.3093, role: "Lake city and Rigi gateway", note: "Compact old town, lakefront, and easy boat connections.", bestFor: "Classic Swiss lake scenery with easy public transport.", allow: "Two nights across July 9 and 10.", dontMiss: ["Chapel Bridge", "Lakefront", "Old town", "Boat pier"], practical: "A station or lakefront hotel makes Rigi day easier.", extraDetails: ["Wake up here for the Rigi loop.", "If Rigi is cloudy, Lucerne still works beautifully."]),
        Place(id: "vitznau", name: "Vitznau", kind: "Lake village transfer", region: "Lake Lucerne", latitude: 47.0105, longitude: 8.4843, role: "Boat-to-cogwheel transfer", note: "Transfer from lake boat to the Rigi cogwheel train.", bestFor: "The scenic hinge from lake deck to mountain railway.", allow: "Connection buffer plus photos.", dontMiss: ["Waterfront", "Cogwheel station"], practical: "Match boat arrival to cogwheel departure.", extraDetails: ["Mostly a transfer, but a very pretty one.", "Keep enough time for the connection."]),
        Place(id: "rigi", name: "Rigi Kulm", kind: "Mountain summit viewpoint", region: "Mt. Rigi", latitude: 47.0569, longitude: 8.4851, role: "360-degree lake and Alp panorama", note: "A simple public-transport mountain summit.", bestFor: "Big first panorama without a hard hike.", allow: "1-2 summit hours.", dontMiss: ["Summit", "Lake views", "Short paths"], practical: "Bring a wind layer even in July.", extraDetails: ["A forgiving first mountain day.", "Return side can adapt by timetable."]),
        Place(id: "interlaken", name: "Interlaken Ost", kind: "Rail and boat hub", region: "Bernese Oberland", latitude: 46.6906, longitude: 7.8697, role: "Rail, boat, and mountain hub", note: "Transfer point for Lauterbrunnen, Lake Brienz, and Bern.", bestFor: "Connections, lockers, Lake Brienz boats, and Harder Kulm.", allow: "30-60 transfer minutes.", dontMiss: ["Station", "Boat pier", "Aare"], practical: "Use Interlaken Ost, not Interlaken West, for these routes.", extraDetails: ["Treat it as the switchboard.", "This is where timing and luggage decisions matter."]),
        Place(id: "lauterbrunnen", name: "Lauterbrunnen", kind: "Alpine valley village", region: "Jungfrau region", latitude: 46.5935, longitude: 7.9091, role: "Two-night mountain base", note: "Valley base for waterfalls, Mürren, Schilthorn, and Jungfraujoch.", bestFor: "Sleeping inside the valley scenery.", allow: "Two nights.", dontMiss: ["Staubbach Falls", "Valley floor", "Trümmelbach option"], practical: "Book lodging early and travel light.", extraDetails: ["The emotional center of the itinerary.", "Two nights protect the mountain day from weather."]),
        Place(id: "murren", name: "Mürren", kind: "Car-free cliff village", region: "Jungfrau region", latitude: 46.5595, longitude: 7.8921, role: "Easy scenic viewpoint", note: "A car-free balcony village with Eiger, Mönch, and Jungfrau views.", bestFor: "Huge views without committing to a costly summit.", allow: "2-4 hours.", dontMiss: ["Village lanes", "Peak views", "Cafe stop"], practical: "Check which access route is operating best.", extraDetails: ["A great first Jungfrau-region viewpoint.", "Also useful as a cloudy-day fallback."]),
        Place(id: "schilthorn", name: "Schilthorn", kind: "Mountain summit viewpoint", region: "Piz Gloria", latitude: 46.5575, longitude: 7.8352, role: "Simpler big-mountain choice", note: "Cable-car summit with Birg Thrill Walk and Bond history.", bestFor: "A dramatic high viewpoint with simpler logistics.", allow: "Half to most of a day.", dontMiss: ["Birg", "Piz Gloria", "Cable-car views"], practical: "Use webcams before committing.", extraDetails: ["Default big-mountain option.", "Less glacier-iconic than Jungfraujoch but easier."]),
        Place(id: "jungfraujoch", name: "Jungfraujoch", kind: "High-Alpine glacier station", region: "Top of Europe", latitude: 46.5475, longitude: 7.9854, role: "Glacier bucket-list choice", note: "High-Alpine rail station and glacier viewpoint.", bestFor: "The most iconic glacier experience.", allow: "Most of the day.", dontMiss: ["Sphinx", "Aletsch Glacier", "Ice Palace"], practical: "Only buy if visibility is strong.", extraDetails: ["The expensive weather-sensitive upgrade.", "Treat as a deliberate choice, not automatic."]),
        Place(id: "brienz", name: "Lake Brienz", kind: "Lake / boat cruise", region: "Turquoise lake day", latitude: 46.727, longitude: 7.97, role: "Boat cruise option", note: "Glacial turquoise lake between Interlaken and Brienz.", bestFor: "A lower-altitude scenic reset day.", allow: "2-4 hours.", dontMiss: ["Turquoise water", "Boat deck", "Brienz village"], practical: "Check boat frequency before locking timing.", extraDetails: ["Helps avoid mountain fatigue.", "Build around the Bern transfer."]),
        Place(id: "harder", name: "Harder Kulm", kind: "Funicular viewpoint", region: "Top of Interlaken", latitude: 46.697, longitude: 7.851, role: "Short funicular viewpoint", note: "Quick viewpoint above Interlaken and the two lakes.", bestFor: "A compact add-on if timing and weather are easy.", allow: "60-90 minutes.", dontMiss: ["Two-lake panorama", "View platform"], practical: "Optional, not core.", extraDetails: ["High reward, short logistics.", "Skip if it risks the Bern transfer."]),
        Place(id: "bern", name: "Bern", kind: "City stopover", region: "Final city", latitude: 46.948, longitude: 7.4474, role: "UNESCO old city stopover", note: "A natural stop between Interlaken and Zurich.", bestFor: "A compact final-night and final-morning city.", allow: "One evening plus morning.", dontMiss: ["Zytglogge", "Arcades", "Cathedral terrace"], practical: "Sleep here after the Oberland.", extraDetails: ["Avoids Zurich-to-Bern backtracking.", "Covered arcades help in rain."]),
        Place(id: "bern-old-city", name: "Bern Old City", kind: "Historic walking area", region: "UNESCO core", latitude: 46.9476, longitude: 7.4515, role: "Walking loop", note: "Arcaded old-town core, clock tower, cafes, and river viewpoints.", bestFor: "A quick-to-relaxed final morning walk.", allow: "2-4 hours.", dontMiss: ["Zytglogge", "Arcades", "Aare views"], practical: "Return to Zurich early if departure is fixed.", extraDetails: ["Prioritize this over trying to cover all Bern.", "Easy to shorten."])
    ]

    static var placeByID: [String: Place] {
        Dictionary(uniqueKeysWithValues: places.map { ($0.id, $0) })
    }

    static let dayPlans: [DayPlan] = [
        DayPlan(id: 1, date: "Thu, Jul 9", title: "Zurich workday, evening to Lucerne", base: "Overnight Lucerne", summary: "Work in Zurich, then take an evening train to Lucerne so the first scenic morning starts by the lake.", jawDrop: "Sunset arrival in Lucerne with lakefront and old town ready for a short walk.", effort: "Very easy", weather: "Works in almost any weather.", route: ["zurich", "lucerne"], legs: [TransitLeg(from: "Zurich work base / Zurich HB", to: "Lucerne", mode: .train, duration: "~45-55 min", guidance: "Travel after work and check into Lucerne.")], highlights: ["Easy Zurich departure", "Lucerne evening", "Rigi setup"], optionalAddOns: [], backup: "If work runs late, take a later direct train.", priceEstimates: [PriceEstimate(label: "Zurich-Lucerne train", estimate: "CHF 15-30+ pp", note: "Verify in SBB."), PriceEstimate(label: "Pass setup", estimate: "CHF 0", note: "Save key routes after check-in.")], reminders: [BookingReminder(label: "Book Lucerne hotel for July 9 and 10", priority: "must"), BookingReminder(label: "Install SBB Mobile", priority: "must")], decisions: []),
        DayPlan(id: 2, date: "Fri, Jul 10", title: "Lucerne and Mt. Rigi", base: "Overnight Lucerne", summary: "Wake up in Lucerne and make the classic lake-and-cogwheel loop to Rigi Kulm.", jawDrop: "Rigi Kulm offers 360-degree lake and Alpine views.", effort: "Easy scenic", weather: "Check summit webcams; stay lower if clouds cover Rigi.", route: ["lucerne", "vitznau", "rigi", "lucerne"], legs: [TransitLeg(from: "Lucerne", to: "Vitznau", mode: .boat, duration: "~1 hr", guidance: "Pick a boat that connects with the cogwheel train."), TransitLeg(from: "Vitznau", to: "Rigi Kulm", mode: .cogwheel, duration: "~35-45 min", guidance: "Ride up for summit views."), TransitLeg(from: "Rigi Kulm", to: "Lucerne", mode: .cogwheel, duration: "~1.5-2 hr", guidance: "Return to Lucerne for the overnight.")], highlights: ["Lucerne lakefront", "Boat approach", "Rigi summit"], optionalAddOns: ["Chapel Bridge / old town walk", "Lake promenade before dinner", "Transport Museum if Rigi is cloudy"], backup: "Lucerne old town, lake cruise, or museum day.", priceEstimates: [PriceEstimate(label: "Swiss Travel Pass option", estimate: "Often covered", note: "Verify 2026 validity."), PriceEstimate(label: "Without pass", estimate: "CHF 65-120+ pp", note: "Approximate before discounts.")], reminders: [BookingReminder(label: "Check Rigi and Lake Lucerne timetables", priority: "verify"), BookingReminder(label: "Rigi does not need advance booking for individuals; groups of 10+ reserve 24 hours ahead", priority: "verify"), BookingReminder(label: "Pack light layer", priority: "must")], decisions: []),
        DayPlan(id: 3, date: "Sat, Jul 11", title: "Panorama train to Lauterbrunnen", base: "Overnight Lauterbrunnen", summary: "Take the Luzern-Interlaken Express, continue into Lauterbrunnen, then visit Mürren.", jawDrop: "Lauterbrunnen stacks cliffs, waterfalls, and peaks into one valley.", effort: "Easy scenic", weather: "Still strong in moody weather.", route: ["lucerne", "interlaken", "lauterbrunnen", "murren", "lauterbrunnen"], legs: [TransitLeg(from: "Lucerne", to: "Interlaken Ost", mode: .train, duration: "~1 hr 50 min", guidance: "Use the Luzern-Interlaken Express."), TransitLeg(from: "Interlaken Ost", to: "Lauterbrunnen", mode: .train, duration: "~20 min", guidance: "Local train into the valley."), TransitLeg(from: "Lauterbrunnen", to: "Mürren", mode: .cableCar, duration: "~25-40 min", guidance: "Use best operating access route."), TransitLeg(from: "Mürren", to: "Lauterbrunnen", mode: .cableCar, duration: "~25-40 min", guidance: "Return for the overnight.")], highlights: ["Panorama train", "Staubbach Falls", "Mürren"], optionalAddOns: ["Mürren evening walk if energy is good", "Staubbach Falls after check-in", "Trümmelbach Falls instead of Mürren if clouds are low"], backup: "Trümmelbach Falls or valley walk.", priceEstimates: [PriceEstimate(label: "Main rail day", estimate: "CHF 40-90+ pp", note: "Varies by pass/saver."), PriceEstimate(label: "Mürren access", estimate: "CHF 10-30+ pp", note: "Depends on route and pass.")], reminders: [BookingReminder(label: "Book Lauterbrunnen lodging", priority: "must"), BookingReminder(label: "Consider Luzern-Interlaken Express seat reservation; July 2026 is CHF 16 pp", priority: "optional")], decisions: []),
        DayPlan(id: 4, date: "Sun, Jul 12", title: "Choose the mountain by visibility", base: "Overnight Lauterbrunnen", summary: "Choose the expensive summit day by webcams and weather.", jawDrop: "Schilthorn is simpler drama; Jungfraujoch is the glacier bucket-list upgrade.", effort: "Easy scenic", weather: "Only commit high if upper stations are clear.", route: ["lauterbrunnen", "murren", "schilthorn", "murren", "lauterbrunnen"], legs: [TransitLeg(from: "Lauterbrunnen", to: "Mürren / Stechelberg access", mode: .cableCar, duration: "~25-45 min", guidance: "Start with best operating access route."), TransitLeg(from: "Mürren / Birg", to: "Schilthorn", mode: .cableCar, duration: "~30-60 min", guidance: "Continue upward if webcams look good."), TransitLeg(from: "Schilthorn", to: "Mürren", mode: .cableCar, duration: "~30-45 min", guidance: "Descend in stages."), TransitLeg(from: "Mürren", to: "Lauterbrunnen", mode: .cableCar, duration: "~25-40 min", guidance: "Return before last connections.")], highlights: ["Webcam decision", "Schilthorn / Birg", "Optional Jungfraujoch"], optionalAddOns: [], backup: "Villages and waterfalls if visibility is poor.", priceEstimates: [PriceEstimate(label: "Schilthorn default", estimate: "CHF 50-110+ pp", note: "Verify discounts."), PriceEstimate(label: "Jungfraujoch upgrade", estimate: "CHF 75-170+ pp", note: "Most expensive day.")], reminders: [BookingReminder(label: "Check webcams before buying", priority: "must"), BookingReminder(label: "If choosing Jungfraujoch, book the mandatory May-Oct 2026 seat reservation after forecast check", priority: "must"), BookingReminder(label: "For Schilthorn, buy only once visibility looks worthwhile; reserve Piz Gloria only for a set table", priority: "optional"), BookingReminder(label: "Price both mountain options", priority: "verify")], decisions: [DecisionOption(title: "Schilthorn", bestFor: "Simpler dramatic summit.", tradeoff: "Less glacier-iconic.", logistics: "Cable cars via Mürren/Birg."), DecisionOption(title: "Jungfraujoch", bestFor: "Glacier bucket list.", tradeoff: "Higher cost and longer day.", logistics: "Rail/cable route toward Eigergletscher.")]),
        DayPlan(id: 5, date: "Mon, Jul 13", title: "Lake Brienz, then Bern", base: "Overnight Bern", summary: "A softer scenic day: Lake Brienz, then continue to Bern.", jawDrop: "Lake Brienz has glacial turquoise water.", effort: "Easy scenic", weather: "Lake day is more forgiving than a peak day.", route: ["lauterbrunnen", "interlaken", "brienz", "interlaken", "bern"], legs: [TransitLeg(from: "Lauterbrunnen", to: "Interlaken Ost", mode: .train, duration: "~20 min", guidance: "Morning transfer; use lockers if helpful."), TransitLeg(from: "Interlaken Ost", to: "Lake Brienz / Brienz", mode: .boat, duration: "Flexible", guidance: "Pick a cruise segment that leaves time for Bern."), TransitLeg(from: "Lake Brienz / Brienz", to: "Interlaken Ost", mode: .boat, duration: "Flexible", guidance: "Return with buffer."), TransitLeg(from: "Interlaken Ost", to: "Bern", mode: .train, duration: "~1 hr", guidance: "Evening transfer to Bern.")], highlights: ["Lake Brienz", "Optional Iseltwald", "Earlier Bern arrival"], optionalAddOns: [], backup: "Skip lake if timing fails and transfer earlier.", priceEstimates: [PriceEstimate(label: "Lake + rail day", estimate: "CHF 45-100+ pp", note: "Verify boat and rail."), PriceEstimate(label: "Harder Kulm add-on", estimate: "CHF 20-45+ pp", note: "Optional only.")], reminders: [BookingReminder(label: "Check Lake Brienz timetable", priority: "verify"), BookingReminder(label: "Lake Brienz scheduled boats do not take seat reservations; buy day-of unless reserving a restaurant table", priority: "verify"), BookingReminder(label: "Harder Kulm can stay day-of; buy only if weather and Bern timing work", priority: "optional"), BookingReminder(label: "Book Bern hotel", priority: "must")], decisions: []),
        DayPlan(id: 6, date: "Tue, Jul 14", title: "Bern morning, Zurich finish", base: "Trip ends Zurich", summary: "Use Bern old city while already there, then return to Zurich.", jawDrop: "Bern old city curves around the Aare with arcades and viewpoints.", effort: "Easy scenic", weather: "Works well in rain thanks to covered arcades.", route: ["bern", "bern-old-city", "bern", "zurich"], legs: [TransitLeg(from: "Bern station", to: "Old City loop", mode: .walk, duration: "2-4 hr", guidance: "Zytglogge, arcades, river viewpoints."), TransitLeg(from: "Old City loop", to: "Bern station", mode: .walk, duration: "~10-20 min", guidance: "Return for luggage and Zurich train."), TransitLeg(from: "Bern", to: "Zurich HB", mode: .train, duration: "~1 hr", guidance: "Keep a generous departure buffer.")], highlights: ["UNESCO Old City", "Zytglogge", "Aare views"], optionalAddOns: [], backup: "Skip the loop if departure is early.", priceEstimates: [PriceEstimate(label: "Bern old city", estimate: "CHF 0-25 pp", note: "Walking is free; budget cafes/lockers."), PriceEstimate(label: "Bern-Zurich rail", estimate: "CHF 20-55+ pp", note: "Varies by ticket/pass.")], reminders: [BookingReminder(label: "Leave Bern early enough", priority: "must"), BookingReminder(label: "Use hotel storage or lockers", priority: "verify")], decisions: [])
    ]

    static let passItems = [
        PassItem(id: "city", label: "Zurich-Lucerne + city transit", swiss: 3, half: 1, saver: 1, point: 1),
        PassItem(id: "rigi", label: "Lucerne boat + Rigi rail day", swiss: 3, half: 2, saver: 2, point: 1),
        PassItem(id: "oberland", label: "Lucerne to Lauterbrunnen rail day", swiss: 3, half: 2, saver: 2, point: 1),
        PassItem(id: "schilthorn", label: "Schilthorn / mountain lifts", swiss: 2, half: 3, saver: 1, point: 1),
        PassItem(id: "lake", label: "Lake Brienz + Interlaken moves", swiss: 3, half: 2, saver: 2, point: 1),
        PassItem(id: "bern", label: "Interlaken-Bern-Zurich rail", swiss: 3, half: 2, saver: 2, point: 1)
    ]

    static let passOptions = [
        PassOption(name: "Swiss Travel Pass", fit: "One simple ticket for trains, boats, city transit, Rigi, museums, and flexibility.", goodFor: "Rigi, boats, city transit, and low admin.", watchOut: "Jungfraujoch/Schilthorn still need discount checks."),
        PassOption(name: "Half Fare Card", fit: "Strong when mountain tickets are expensive and you are fine buying each leg.", goodFor: "Mountain discounts and most public transport.", watchOut: "More ticket admin."),
        PassOption(name: "Saver Day Passes", fit: "Good for fixed long-travel days bought early.", goodFor: "Locked-in rail/boat travel days.", watchOut: "Less flexible."),
        PassOption(name: "Point-to-point", fit: "Only if pass comparison does not pencil out.", goodFor: "Few discounted legs.", watchOut: "This itinerary has many paid transport types.")
    ]

    static let bookingItems = [
        "Lucerne hotel Jul 9-10",
        "Lauterbrunnen hotel",
        "Bern hotel",
        "Rigi / Lake Lucerne timetable check",
        "Mountain-day webcam decision",
        "Lake Brienz boat timetable",
        "Rail pass or ticket strategy"
    ]
}
